name: study_planner
description: A Study Planner app with tasks, calendar, and reminders.

publish_to: 'none' # Remove this if you plan to publish on pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Local storage (save tasks as JSON)
  shared_preferences: ^2.2.2

  # Date and time formatting
  intl: ^0.19.0

  # Optional: SQLite support if you want to upgrade later
  sqflite: ^2.3.0
  path: ^1.8.3

  # Optional: state management for larger apps
  provider: ^6.1.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
